### ISSUE TITLE
Vuetifyの導入でつまづいている

### ISSUE THREAD

**Issue by RyoTanifuji** [RyoTanifuji/smash_notice#5]
### 質問内容・実現したいこと
下記の環境で検証用のアプリを作成し、vuetifyの導入までを検証したかったのですが、エラーで詰まってしまいました。
- Rails 6.1.7.6
- Ruby 3.0.6
- Vue.js 3.2.36
- Node.js 16.17.0
- Yarn 1.22.19

### 現状発生している問題・エラーメッセージ
[公式サイト](https://vuetifyjs.com/en/getting-started/installation/#existing-projects)を参考に
「yarn add vuetify」を実行し、app/javascript/packs/hello_vue.jsに下記のコードを追加
```
import { createApp } from 'vue'
import App from '../app.vue'

import { createVuetify } from 'vuetify' #追加
import 'vuetify/dist/vuetify.min.css' #追加

const vuetify = createVuetify() #追加

document.addEventListener('DOMContentLoaded', () => {
  const selector = '#app';
  if(document.querySelector(selector)){
    createApp(App).use(vuetify).mount(selector); #追加
  }
})
```
その後、サーバーを起動し、アクセスしたところデベロッパーツールとログに以下のエラーが発生し、
vueに関するテキストも表示されなくなりました。
[![Image from Gyazo](https://i.gyazo.com/9e1970006b7346d147cdecbb2366546b.png)](https://gyazo.com/9e1970006b7346d147cdecbb2366546b)

[![Image from Gyazo](https://i.gyazo.com/f46b032ab35818c3f5d04173e5437a79.png)](https://gyazo.com/f46b032ab35818c3f5d04173e5437a79)
[![Image from Gyazo](https://i.gyazo.com/1d776200b02583961262ed8d60546328.png)](https://gyazo.com/1d776200b02583961262ed8d60546328)

### どの処理までうまく動いているのか
[参考記事](https://qiita.com/bumpfuji10/items/40cc7e6a2de2d15d92ca)を参考に、以下のメモの手順でVue.jsを導入し
"Hello, Vue.js 3.0"の表示まではうまくいきました。
[Vue.js導入までの手順](https://rattle-era-339.notion.site/Rails6-1-7-6-Vue-js3-ceb63fbe569e44b5803f6284ba50522d)

### 該当のソースコード
package.json
```
{
  "name": "vuetify-test-app",
  "private": true,
  "dependencies": {
    "@rails/actioncable": "^6.0.0",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
    "@rails/webpacker": "5.4.4",
    "@vue/compiler-sfc": "^3.3.6",
    "turbolinks": "^5.2.0",
    "vue": "^3.2.36",
    "vue-loader": "^17.3.0",
    "vuetify": "^3.3.22",
    "webpack": "^4.46.0",
    "webpack-cli": "^3.3.12"
  },
  "version": "0.1.0",
  "devDependencies": {
    "@babel/plugin-proposal-private-methods": "^7.18.6",
    "@babel/plugin-proposal-private-property-in-object": "^7.21.0",
    "webpack-dev-server": "^3"
  }
}

```
### エラーから考えられる原因
- 適切なローダーがインストールされていない
- ローダーの設定が間違っており、読み込めていない
- バージョンの合っていないライブラリなどがある

### 試したこと
試しにnode.jsのバージョンを17系に上げてみたところ、vue.jsの導入の段階で「node.jsのバージョンが高い」という旨のエラーが出てしまったので、元のバージョンに戻しました。

以下の記事を参考に
[参考記事](https://qiita.com/shizen-shin/items/83790c05cb225528f671)
```
yarn add --dev sass sass-loader deepmerge
```
を実行し、config/webpack/environment.jsに以下の記述を追加しました。
```
environment.loaders.prepend('sass', {
  test: /\.s(c|a)ss$/,
  use: [
    'style-loader',
    'css-loader',
    {
      loader: 'sass-loader',
      options: {
        implementation: require('sass'),
        sassOptions: {
          indentedSyntax: true
        },
      },
    },
  ],
});
```
上記を実行してもエラー内容が変わらず、参考になりそうな記事も見つけられなかったため、
ご助言いただけるとありがたいです。

**Comment by kenchasonakai** [comment]
Vue3系のバージョンによってはVuetify対応していないとかがあると思うので(確かVue3系の最初の方はVuetifyまだ対応していないとか言われてた気がします)VueのバージョンとNodeのバージョンをあげて対応してみるのが良いかなとは思います

**Comment by RyoTanifuji** [comment]
アドバイスありがとうございます。
以下のバージョンの組み合わせを試してみました。
node 16.17.0 vue 3.1.5
node 17.9.1 vue 3.3.4
node 18.16.0 vue 3.2.36
node 18.16.0 vue 3.3.2
node 19.1.0 vue 3.3.2
サーバーログのエラーは出たり出なかったりしたのですが、デベロッパーツールのエラーは上記と同様のものが一貫して出ていました。また、vueに関するテキストも表示されなかったです。
vuetifyのバージョンを下げたりもしてみたのですが、結果は同じでした。

調べる過程でwebpack-plugin-vuetifyというライブラリも試してみたのですが、同様のエラーが出ていました。

以下は現時点のpackage.jsonです。（nodeのバージョンはとりあえず16.17.0に戻しています）
```
{
  "name": "vuetify-test-app",
  "private": true,
  "dependencies": {
    "@rails/actioncable": "^6.0.0",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
    "@rails/webpacker": "5.4.4",
    "@vue/compiler-sfc": "^3.3.7",
    "turbolinks": "^5.2.0",
    "vue": "^3.2.36",
    "vue-loader": "^17.3.0",
    "vuetify": "^3.0.7",
    "webpack": "^4.46.0",
    "webpack-cli": "^3.3.12",
    "webpack-plugin-vuetify": "^2.0.1"
  },
  "version": "0.1.0",
  "devDependencies": {
    "@babel/plugin-proposal-private-methods": "^7.18.6",
    "@babel/plugin-proposal-private-property-in-object": "^7.21.0",
    "webpack-dev-server": "^3"
  }
}
```

アドバイスの通り試した結果、nodeやvueのバージョンではなさそうと分かったので、
次は以下の記事を参考にbabel-loaderのバージョンを試してみようと思っているのですが、
config/webpack/environment.jsへの設定の追加が分からず手が止まっています。
[webpackでbabel-loaderを使う方法](https://solomaker.club/how-to-use-babel-loader-in-webpack/)

上記の方針で良いか、良い場合はどのように記述するのかを教えていただきたいです。
お手数おかけしますが、よろしくお願いします。

**Comment by kenchasonakai** [comment]
WebpackerはハマりがちなのでRails6系ではなく7系で試してみてもいいかもですね
https://mailsnag.com/blog/rails7-vuetify3/

**Comment by RyoTanifuji** [comment]
Rails7でのvueの導入はimportmapを用いたものしか参考になりそうなものを見つけられていなかったので、
紹介いただいた記事を参考にRails7系でやってみようと思います。
対応時間外であるにも関わらず、ありがとうございました。
