### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [RyoTanifuji/smash_notice#68]
MVPリリースお疲れ様でした。
以下レビュー内容になります。

---

■READMEから課題解決する実装がされているか＆動いているか
・確認できました。LGTMです。

■改善の提案
◯「攻略メモ」と「キャラ対メモ」の使い分けが、初めてサービスを触るユーザーには使い分けや、なぜ分けられているのかが掴みづらいように感じました。以下、思いつきの案ですが参考になれば幸いです。
　・初期データを多くして、それを見れば新規のユーザーでもイメージしやすくしておくとかで改善されないか検討してみてください。
　・メニューを押して表示されるページに、短い説明を加えるとか、ヒントアイコンを押すとポップアップで、どういった使い方をすればいいかがユーザーに伝わる動画が流れるetc

◯「攻略メモ」「キャラ対メモ」ページ遷移後に、フォルダー作成して、そこからメモを作っていくというのが初見では分からなかったため、こちらも上記に記載したような方法などで、ユーザーが使い方が分からなくて立ち止まってしまわない工夫ができるとより良いかと思いました。

---

全体的にシンプルで良かったかと思います。
技術の方も一定レベルに達していると感じました。
そのまま就活に臨んでも問題ないレベルですので、残りの開発と並行して就活の準備に取り組みましょう！

**Comment by Tsuchiya2** [comment]
--- 追記 ---
本リリースの大まかな日取りを教えてください。
よろしくお願いいたします。

**Comment by RyoTanifuji** [comment]
レビューありがとうございます。参考にさせていただきます。
本リリースは1月22日を予定しており、以下の機能を実装する予定です。
（READMEの「その後の機能」と異なっており申し訳ないですが、公開を早めてユーザーの反応などを見たいと思い変更しました。）
- わかりづらい部分の改善
- Google Analytics、メタタグ、OGPの設定
- プロフィール編集機能
- パンくず機能

**Comment by Tsuchiya2** [comment]
回答ありがとうございます。
上記確認しました。引き続き開発頑張ってください！

**Comment by RyoTanifuji** [comment]
ありがとうございます！がんばります！
